import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.database.session import SessionLocal
from app.models.product_master import ProductMotif

MOTIFS = [
    {"id": 1, "name": "GRANDMASTER SEI", "code": "GM_SEI", "description": "Grandmaster SEI"},
    {"id": 2, "name": "GRANDMASTER FULL SERIES", "code": "GM_FS", "description": "Grandmaster Full Series"},
    {"id": 3, "name": "GRANDMASTER EXCLUSIVE BLACK", "code": "GM_EB", "description": "Grandmaster Exclusive Black"},
    {"id": 4, "name": "GRANDMASTER SGE", "code": "GM_SGE", "description": "Grandmaster SGE"},
    {"id": 5, "name": "GRANDMASTER SJL", "code": "GM_SJL", "description": "Grandmaster SJL"},
    {"id": 6, "name": "GRANDMASTER BATIK", "code": "GM_BT", "description": "Grandmaster Batik"},
    {"id": 7, "name": "GRANDMASTER JACQUARD BATIK", "code": "GM_JB", "description": "Grandmaster Jacquard Batik"},
    {"id": 8, "name": "GRANDMASTER 210", "code": "GM_210", "description": "Grandmaster 210"},
    {"id": 9, "name": "PRIMER JACQUARD SONGKET DOMPET", "code": "PR_JSD", "description": "Primer Jacquard Songket Dompet"},
    {"id": 10, "name": "PRIMER DOBBY SONGKET EXCELLENT", "code": "PR_DSE", "description": "Primer Dobby Songket Excellent"},
    {"id": 11, "name": "PRIMER NATURAL", "code": "PR_NAT", "description": "Primer Natural"},
    {"id": 12, "name": "PRIMER KEMBANG SONGKET", "code": "PR_KS", "description": "Primer Kembang Songket"},
    {"id": 13, "name": "PRIMER MEMORIES", "code": "PR_MEM", "description": "Primer Memories"},
    {"id": 14, "name": "PRIMER SONGKET PANORAMA", "code": "PR_SP", "description": "Primer Songket Panorama"},
    {"id": 15, "name": "PRIMER EXCELLENT", "code": "PR_EX", "description": "Primer Excellent"},
    {"id": 16, "name": "BEST", "code": "BEST", "description": "Best"},
    {"id": 17, "name": "BORDIR", "code": "BDR", "description": "Bordir"},
    {"id": 18, "name": "BORDIR BLACK SERIES", "code": "BDR_BS", "description": "Bordir Black Series"},
    {"id": 19, "name": "PANORAMA", "code": "PNR", "description": "Panorama"},
    {"id": 20, "name": "STRIMIN", "code": "STM", "description": "Strimin"},
    {"id": 21, "name": "STRIMIN BLACK SERIES", "code": "STM_BS", "description": "Strimin Black Series"},
    {"id": 22, "name": "MEMORIES", "code": "MEM", "description": "Memories"},
    {"id": 23, "name": "VISCOSE", "code": "VSC", "description": "Viscose"},
    {"id": 24, "name": "VISCOSE WARNA", "code": "VSC_WR", "description": "Viscose Warna"},
    {"id": 25, "name": "VISCOSE HITAM", "code": "VSC_HT", "description": "Viscose Hitam"},
    {"id": 26, "name": "VISCOSE BATIK", "code": "VSC_BT", "description": "Viscose Batik"},
    {"id": 27, "name": "VISCOSE FULL COLOUR", "code": "VSC_FC", "description": "Viscose Full Colour"},
    {"id": 28, "name": "VISCOSE ETERNITY", "code": "VSC_ET", "description": "Viscose Eternity"},
    {"id": 29, "name": "ELITE VISCOSE", "code": "EL_VSC", "description": "Elite Viscose"},
    {"id": 30, "name": "KEMBANG BORNEO", "code": "KBR", "description": "Kembang Borneo"},
    {"id": 31, "name": "VISCOSE PUTIH TUMPAL KEMBANG", "code": "VSC_PTK", "description": "Viscose Putih Tumpal Kembang"},
    {"id": 32, "name": "VISCOSE LILIN KEMBANG", "code": "VSC_LK", "description": "Viscose Lilin Kembang"},
    {"id": 33, "name": "VISCOSE PUTIH LILIN KEMBANG", "code": "VSC_PLK", "description": "Viscose Putih Lilin Kembang"},
    {"id": 34, "name": "NATUNA", "code": "NTN", "description": "Natuna"},
    {"id": 35, "name": "DOBBY 210", "code": "DB_210", "description": "Dobby 210"},
    {"id": 36, "name": "DOBBY GERIMIS", "code": "DB_GR", "description": "Dobby Gerimis"},
    {"id": 37, "name": "JACQUARD CLASSIC", "code": "JC_CL", "description": "Jacquard Classic"},
    {"id": 38, "name": "JACQUARD MASCOT 555", "code": "JC_M555", "description": "Jacquard Mascot 555"},
    {"id": 39, "name": "JACQUARD ANTIK", "code": "JC_AT", "description": "Jacquard Antik"},
    {"id": 40, "name": "JACQUARD DOLPHIN", "code": "JC_DL", "description": "Jacquard Dolphin"},
    {"id": 41, "name": "JACQUARD BORDIR", "code": "JC_BDR", "description": "Jacquard Bordir"},
    {"id": 42, "name": "JACQUARD SINGGASANA", "code": "JC_SG", "description": "Jacquard Singgasana"},
    {"id": 43, "name": "JACQUARD PLATINUM SONGKET", "code": "JC_PS", "description": "Jacquard Platinum Songket"},
    {"id": 44, "name": "JACQUARD BLUDRU BIRU MOTIF TENUN IKAT", "code": "JC_BTI", "description": "Jacquard Bludru Biru Motif Tenun Ikat"},
    {"id": 45, "name": "JACQUARD BATIK", "code": "JC_BT", "description": "Jacquard Batik"},
    {"id": 46, "name": "JACQUARD REALITY", "code": "JC_RL", "description": "Jacquard Reality"},
    {"id": 47, "name": "KEMBANG MERCERISED", "code": "KM_MR", "description": "Kembang Mercerised"},
    {"id": 48, "name": "MASTER QUALITY", "code": "MQ", "description": "Master Quality"},
    {"id": 49, "name": "BALI PRINT", "code": "BP", "description": "Bali Print"},
    {"id": 50, "name": "BALI GOLD", "code": "BG", "description": "Bali Gold"},
    {"id": 51, "name": "BALI SILVER", "code": "BS", "description": "Bali Silver"},
    {"id": 52, "name": "BALIMOON 666", "code": "BM666", "description": "Balimoon 666"},
    {"id": 53, "name": "BALIMOON 777", "code": "BM777", "description": "Balimoon 777"},
    {"id": 54, "name": "BALIMOON MANIK-MANIK", "code": "BM_MM", "description": "Balimoon Manik-Manik"},
    {"id": 55, "name": "BALIMOON CLASSIC", "code": "BM_CL", "description": "Balimoon Classic"},
    {"id": 56, "name": "BALIMOON KAWUNG", "code": "BM_KW", "description": "Balimoon Kawung"},
    {"id": 57, "name": "BALIMOON HARMONIS", "code": "BM_HR", "description": "Balimoon Harmonis"},
    {"id": 58, "name": "BALIMOON STARIA", "code": "BM_ST", "description": "Balimoon Staria"},
    {"id": 59, "name": "BALIMOON LURIK", "code": "BM_LR", "description": "Balimoon Lurik"},
    {"id": 60, "name": "BALIMOON MADRAS", "code": "BM_MD", "description": "Balimoon Madras"},
    {"id": 61, "name": "BALIMOON NEW", "code": "BM_NEW", "description": "Balimoon New"},
    {"id": 62, "name": "BALIMOON TEMPEAN", "code": "BM_TMP", "description": "Balimoon Tempean"},
    {"id": 63, "name": "BALIMOON TERATAI", "code": "BM_TRT", "description": "Balimoon Teratai"},
    {"id": 64, "name": "NALIMOON TOP", "code": "NM_TOP", "description": "Nalimoon Top"},
    {"id": 65, "name": "BALIMOON 66 (DOUBLE SIX)", "code": "BM66", "description": "Balimoon Double Six"},
    {"id": 66, "name": "BALIMOON 999", "code": "BM999", "description": "Balimoon 999"},
    {"id": 67, "name": "BALIMOON 999 PINTU ACEH", "code": "BM999_PA", "description": "Balimoon 999 Pintu Aceh"},
    {"id": 68, "name": "BALIMOON HORIZON MANIK-MANIK", "code": "BM_HMM", "description": "Balimoon Horizon Manik-Manik"},
    {"id": 69, "name": "BALIMOON PEN (PINTO ACEH)", "code": "BM_PPA", "description": "Balimoon Pen (Pinto Aceh)"},
    {"id": 70, "name": "BALI", "code": "BALI", "description": "Bali"},
    {"id": 71, "name": "BALI BLACK", "code": "BALI_BL", "description": "Bali Black"},
    {"id": 72, "name": "BALI HORIZON", "code": "BALI_HR", "description": "Bali Horizon"},
    {"id": 73, "name": "BALI MUSTAMIN", "code": "BALI_MS", "description": "Bali Mustamin"},
    {"id": 74, "name": "BALI OK", "code": "BALI_OK", "description": "Bali OK"},
    {"id": 75, "name": "BALI 555", "code": "BALI_555", "description": "Bali 555"},
    {"id": 76, "name": "BALI BOTOLAN", "code": "BALI_BT", "description": "Bali Botolan"},
    {"id": 77, "name": "BALI DIAMOND", "code": "BALI_DM", "description": "Bali Diamond"},
    {"id": 78, "name": "BALI JINGGA", "code": "BALI_JG", "description": "Bali Jingga"},
    {"id": 79, "name": "BALI JUMPUTAN", "code": "BALI_JM", "description": "Bali Jumputan"},
    {"id": 80, "name": "BALI JUMPUTAN POLOS", "code": "BALI_JP", "description": "Bali Jumputan Polos"},
    {"id": 81, "name": "BALI NICE", "code": "BALI_NC", "description": "Bali Nice"},
    {"id": 82, "name": "BALI ROSE", "code": "BALI_RS", "description": "Bali Rose"},
    {"id": 83, "name": "BALI UNIQ", "code": "BALI_UN", "description": "Bali Uniq"},
    {"id": 84, "name": "BALI WIDURI", "code": "BALI_WD", "description": "Bali Widuri"},
    {"id": 85, "name": "BALI KU", "code": "BALI_KU", "description": "Bali Ku"},
    {"id": 86, "name": "BALI TERATAI", "code": "BALI_TR", "description": "Bali Teratai"},
    {"id": 87, "name": "SONGKET MILLENIUM", "code": "SG_ML", "description": "Songket Millenium"},
    {"id": 88, "name": "SONGKET MELAYU", "code": "SG_MY", "description": "Songket Melayu"},
    {"id": 89, "name": "SONGKET GUNUNGAN", "code": "SG_GN", "description": "Songket Gunungan"},
    {"id": 90, "name": "SONGKET HAWAI", "code": "SG_HW", "description": "Songket Hawai"},
    {"id": 91, "name": "SONGKET TIGA DARA TIMBUL", "code": "SG_TDT", "description": "Songket Tiga Dara Timbul"},
    {"id": 92, "name": "SONGKET REMBULAN", "code": "SG_RB", "description": "Songket Rembulan"},
    {"id": 93, "name": "SONGKET HORIZON", "code": "SG_HR", "description": "Songket Horizon"},
    {"id": 94, "name": "SONGKET RAINBOW", "code": "SG_RW", "description": "Songket Rainbow"},
    {"id": 95, "name": "SONGKET TIKAR BUGIS", "code": "SG_TB", "description": "Songket Tikar Bugis"},
    {"id": 96, "name": "SONGKET CCT", "code": "SG_CCT", "description": "Songket CCT"},
    {"id": 97, "name": "SONGKET MANISE", "code": "SG_MN", "description": "Songket Manise"},
    {"id": 98, "name": "SONGKET BETAWI", "code": "SG_BW", "description": "Songket Betawi"},
    {"id": 99, "name": "SONGKET GERIMIS PEN", "code": "SG_GP", "description": "Songket Gerimis Pen"},
    {"id": 100, "name": "SONGKET BINTANG", "code": "SG_BG", "description": "Songket Bintang"},
    {"id": 101, "name": "GERIMIS MULTICOLOUR", "code": "GR_MC", "description": "Gerimis Multicolour"},
    {"id": 102, "name": "KEMBANG MULTICOLOUR", "code": "KB_MC", "description": "Kembang Multicolour"},
    {"id": 103, "name": "KEMBANG JENTIK MANIS", "code": "KB_JM", "description": "Kembang Jentik Manis"},
    {"id": 104, "name": "KEMBANG SALJU", "code": "KB_SJ", "description": "Kembang Salju"},
    {"id": 105, "name": "TUMPAL KEMBANG", "code": "TK", "description": "Tumpal Kembang"},
    {"id": 106, "name": "TUMPAL KEMBANG WHITE EDITION", "code": "TK_WE", "description": "Tumpal Kembang White Edition"},
    {"id": 107, "name": "TUMPAL KEMBANG TIGA DARA", "code": "TK_TD", "description": "Tumpal Kembang Tiga Dara"},
    {"id": 108, "name": "TUMPAL KEMBANG POLOS", "code": "TK_PL", "description": "Tumpal Kembang Polos"},
    {"id": 109, "name": "TUMPAL KEMBANG POLOS PUTIH", "code": "TK_PP", "description": "Tumpal Kembang Polos Putih"},
    {"id": 110, "name": "TUMPAL KEMBANG MANIK-MANIK", "code": "TK_MM", "description": "Tumpal Kembang Manik-Manik"},
    {"id": 111, "name": "TUMPAL KEMBANG HAWAI", "code": "TK_HW", "description": "Tumpal Kembang Hawai"},
    {"id": 112, "name": "TUMPAL KEMBANG MANISE", "code": "TK_MN", "description": "Tumpal Kembang Manise"},
    {"id": 113, "name": "TUMPAL KEMBANG LURIK", "code": "TK_LR", "description": "Tumpal Kembang Lurik"},
    {"id": 114, "name": "GERIMIS 777 SERI HITAM", "code": "GR777_SH", "description": "Gerimis 777 Seri Hitam"},
    {"id": 115, "name": "GERIMIS 777 SERI PUTIH", "code": "GR777_SP", "description": "Gerimis 777 Seri Putih"},
    {"id": 116, "name": "GERIMIS 777 TIGA DARA", "code": "GR777_TD", "description": "Gerimis 777 Tiga Dara"},
    {"id": 117, "name": "GERIMIS 777 KOTAK", "code": "GR777_KT", "description": "Gerimis 777 Kotak"},
    {"id": 118, "name": "GERIMIS 777 MANIK-MANIK", "code": "GR777_MM", "description": "Gerimis 777 Manik-Manik"},
    {"id": 119, "name": "HGG JARI JARI", "code": "HGG_JJ", "description": "HGG Jari Jari"},
    {"id": 120, "name": "GERIMIS KMB MULTI COLOUR", "code": "GR_KMC", "description": "Gerimis KMB Multi Colour"},
    {"id": 121, "name": "POLOS", "code": "PL", "description": "Polos"},
    {"id": 122, "name": "VERTIKAL", "code": "VT", "description": "Vertikal"},
    {"id": 123, "name": "DUA WARNA", "code": "DW", "description": "Dua Warna"},
    {"id": 124, "name": "LUXURY", "code": "LX", "description": "Luxury"},
    {"id": 125, "name": "LUXURY PEN", "code": "LX_PN", "description": "Luxury Pen"},
    {"id": 126, "name": "RELIEF", "code": "RL", "description": "Relief"},
    {"id": 127, "name": "RELIEF PEN", "code": "RL_PN", "description": "Relief Pen"},
    {"id": 128, "name": "RELIEF SOFT COLOUR", "code": "RL_SC", "description": "Relief Soft Colour"},
    {"id": 129, "name": "TIMBUL POLOS TUMPAL FULL", "code": "TB_PTF", "description": "Timbul Polos Tumpal Full"},
    {"id": 130, "name": "TIMBUL POLOS TUMPAL", "code": "TB_PT", "description": "Timbul Polos Tumpal"},
    {"id": 131, "name": "TIMBUL KOTAK", "code": "TB_KT", "description": "Timbul Kotak"},
    {"id": 132, "name": "TIMBUL RAINBOW", "code": "TB_RW", "description": "Timbul Rainbow"},
    {"id": 133, "name": "TIMBUL TIGA DARA", "code": "TB_TD", "description": "Timbul Tiga Dara"},
    {"id": 134, "name": "TIMBUL HORIZON", "code": "TB_HR", "description": "Timbul Horizon"},
    {"id": 135, "name": "TIMBUL MANIK-MANIK", "code": "TB_MM", "description": "Timbul Manik-Manik"},
    {"id": 136, "name": "TIMBUL HITAM PUTIH", "code": "TB_HP", "description": "Timbul Hitam Putih"},
    {"id": 137, "name": "SULAM KOTAK", "code": "SL_KT", "description": "Sulam Kotak"},
    {"id": 138, "name": "SULAM LILIN", "code": "SL_LL", "description": "Sulam Lilin"},
    {"id": 139, "name": "SULAM HAWAI", "code": "SL_HW", "description": "Sulam Hawai"},
    {"id": 140, "name": "SULAM HORIZON", "code": "SL_HR", "description": "Sulam Horizon"},
    {"id": 141, "name": "SULAM TEMANTEN", "code": "SL_TM", "description": "Sulam Temanten"},
    {"id": 142, "name": "ORIENTAL", "code": "ORI", "description": "Oriental"},
    {"id": 143, "name": "DJARING", "code": "DJR", "description": "Djaring"},
    {"id": 144, "name": "EQUALIZER", "code": "EQL", "description": "Equalizer"},
    {"id": 145, "name": "LURIEK", "code": "LRK", "description": "Luriek"},
    {"id": 146, "name": "MOZAIC", "code": "MZC", "description": "Mozaic"},
    {"id": 147, "name": "ONYXE", "code": "ONX", "description": "Onyxe"},
    {"id": 148, "name": "SYAVANA", "code": "SYV", "description": "Syavana"},
    {"id": 149, "name": "BATIK GUS MASTER QUALITY MERCERIZED", "code": "BT_GMQ_M", "description": "Batik Gus Master Quality Mercerized"},
    {"id": 150, "name": "JAWA BATIK", "code": "JB", "description": "Jawa Batik"},
    {"id": 151, "name": "BATIK JAWA KUNO", "code": "BJK", "description": "Batik Jawa Kuno"},
    {"id": 152, "name": "BATIK WAKANDA", "code": "BW", "description": "Batik Wakanda"},
    {"id": 153, "name": "JUNIOR BATIK", "code": "JB", "description": "Junior Batik"},
    {"id": 154, "name": "G.M.C GJA COLOUR SERIES", "code": "GMC_GJA_CS", "description": "G.M.C GJA Colour Series"},
    {"id": 155, "name": "G.M.C GJA BLACK SERIES", "code": "GMC_GJA_BS", "description": "G.M.C GJA Black Series"},
    {"id": 156, "name": "G.M.C GJB COLOUR SERIES", "code": "GMC_GJB_CS", "description": "G.M.C GJB Colour Series"},
    {"id": 157, "name": "G.M.C GJB BLACK SERIES", "code": "GMC_GJB_BS", "description": "G.M.C GJB Black Series"},
    {"id": 158, "name": "G.M.C GJC COLOUR SERIES", "code": "GMC_GJC_CS", "description": "G.M.C GJC Colour Series"},
    {"id": 159, "name": "G.M.C GJC BLACK SERIES", "code": "GMC_GJC_BS", "description": "G.M.C GJC Black Series"},
    {"id": 160, "name": "G.M.C GJD COLOUR SERIES", "code": "GMC_GJD_CS", "description": "G.M.C GJD Colour Series"},
    {"id": 161, "name": "G.M.C GJD BLACK SERIES", "code": "GMC_GJD_BS", "description": "G.M.C GJD Black Series"},
    {"id": 162, "name": "G.M.C GJO COLOUR SERIES", "code": "GMC_GJO_CS", "description": "G.M.C GJO Colour Series"},
    {"id": 163, "name": "G.M.C GJO BLACK SERIES", "code": "GMC_GJO_BS", "description": "G.M.C GJO Black Series"},
    {"id": 164, "name": "G.M.C GSE COLOUR SERIES", "code": "GMC_GSE_CS", "description": "G.M.C GSE Colour Series"},
    {"id": 165, "name": "G.M.C GSE BLACK SERIES", "code": "GMC_GSE_BS", "description": "G.M.C GSE Black Series"},
    {"id": 166, "name": "G.M.C GSV COLOUR SERIES", "code": "GMC_GSV_CS", "description": "G.M.C GSV Colour Series"},
    {"id": 167, "name": "G.M.C GSV BLACK SERIES", "code": "GMC_GSV_BS", "description": "G.M.C GSV Black Series"},
    {"id": 168, "name": "G.M.C GTB COLOUR SERIES", "code": "GMC_GTB_CS", "description": "G.M.C GTB Colour Series"},
    {"id": 169, "name": "G.M.C GTB BLACK SERIES", "code": "GMC_GTB_BS", "description": "G.M.C GTB Black Series"},
    {"id": 170, "name": "G.M.C GVA COLOUR SERIES", "code": "GMC_GVA_CS", "description": "G.M.C GVA Colour Series"},
    {"id": 171, "name": "G.M.C GVA BLACK SERIES", "code": "GMC_GVA_BS", "description": "G.M.C GVA Black Series"},
    {"id": 172, "name": "G.M.C SGJ COLOUR SERIES", "code": "GMC_SGJ_CS", "description": "G.M.C SGJ Colour Series"},
    {"id": 173, "name": "G.M.C SGJ BLACK SERIES", "code": "GMC_SGJ_BS", "description": "G.M.C SGJ Black Series"},
    {"id": 174, "name": "PASUNDAN - ARGAPURA (BLACK SERIES)", "code": "PS_ARGA_BS", "description": "PASUNDAN - ARGAPURA (BLACK SERIES)"},
    {"id": 175, "name": "PASUNDAN - ARGAPURA (COLOUR SERIES)", "code": "PS_ARGA_CS", "description": "PASUNDAN - ARGAPURA (COLOUR SERIES)"},
    {"id": 176, "name": "PASUNDAN - GALUNGGUNG (BLACK SERIES)", "code": "PS_GALU_BS", "description": "PASUNDAN - GALUNGGUNG (BLACK SERIES)"},
    {"id": 177, "name": "PASUNDAN - GALUNGGUNG (COLOUR SERIES)", "code": "PS_GALU_CS", "description": "PASUNDAN - GALUNGGUNG (COLOUR SERIES)"},
    {"id": 178, "name": "PASUNDAN - HALIMUN (BLACK SERIES)", "code": "PS_HALI_BS", "description": "PASUNDAN - HALIMUN (BLACK SERIES)"},
    {"id": 179, "name": "PASUNDAN - HALIMUN (COLOUR SERIES)", "code": "PS_HALI_CS", "description": "PASUNDAN - HALIMUN (COLOUR SERIES)"},
    {"id": 180, "name": "PASUNDAN - HARUMAN (BLACK SERIES)", "code": "PS_HARU_BS", "description": "PASUNDAN - HARUMAN (BLACK SERIES)"},
    {"id": 181, "name": "PASUNDAN - HARUMAN (COLOUR SERIES)", "code": "PS_HARU_CS", "description": "PASUNDAN - HARUMAN (COLOUR SERIES)"},
    {"id": 182, "name": "PASUNDAN - PANGANDARAN (BLACK SERIES)", "code": "PS_PANG_BS", "description": "PASUNDAN - PANGANDARAN (BLACK SERIES)"},
    {"id": 183, "name": "PASUNDAN - PANGANDARAN (COLOUR SERIES)", "code": "PS_PANG_CS", "description": "PASUNDAN - PANGANDARAN (COLOUR SERIES)"},
    {"id": 184, "name": "PASUNDAN - PANGRANGO (BLACK SERIES)", "code": "PS_PANGR_BS", "description": "PASUNDAN - PANGRANGO (BLACK SERIES)"},
    {"id": 185, "name": "PASUNDAN - PANGRANGO (COLOUR SERIES)", "code": "PS_PANGR_CS", "description": "PASUNDAN - PANGRANGO (COLOUR SERIES)"},
    {"id": 186, "name": "PASUNDAN - TANGKUBAN (BLACK SERIES)", "code": "PS_TANG_BS", "description": "PASUNDAN - TANGKUBAN (BLACK SERIES)"},
    {"id": 187, "name": "PASUNDAN - TANGKUBAN (COLOUR SERIES)", "code": "PS_TANG_CS", "description": "PASUNDAN - TANGKUBAN (COLOUR SERIES)"},
    {"id": 188, "name": "PASUNDAN - BURANGRANG (BLACK SERIES)", "code": "PS_BURA_BS", "description": "PASUNDAN - BURANGRANG (BLACK SERIES)"},
    {"id": 189, "name": "PASUNDAN - BURANGRANG (COLOUR SERIES)", "code": "PS_BURA_CS", "description": "PASUNDAN - BURANGRANG (COLOUR SERIES)"},
    {"id": 190, "name": "PASUNDAN - CIBODAS (BLACK SERIES)", "code": "PS_CIBO_BS", "description": "PASUNDAN - CIBODAS (BLACK SERIES)"},
    {"id": 191, "name": "PASUNDAN - CIBODAS (COLOUR SERIES)", "code": "PS_CIBO_CS", "description": "PASUNDAN - CIBODAS (COLOUR SERIES)"},
    {"id": 192, "name": "PASUNDAN - CIHERANG - BLACK SERIES", "code": "PS_CIHE_BS", "description": "PASUNDAN - CIHERANG - BLACK SERIES"},
    {"id": 193, "name": "PASUNDAN - CIHERANG - COLOUR SERIES", "code": "PS_CIHE_CS", "description": "PASUNDAN - CIHERANG - COLOUR SERIES"},
    {"id": 194, "name": "PASUNDAN - CIKURAI - BLACK SERIES", "code": "PS_CIKU_BS", "description": "PASUNDAN - CIKURAI - BLACK SERIES"},
    {"id": 195, "name": "PASUNDAN - CIKURAI", "code": "PS_CIKU_CS", "description": "PASUNDAN - CIKURAI"},
    {"id": 196, "name": "PASUNDAN - CIREMAI  (COLOUR SERIES)", "code": "PS_CIRE_CS", "description": "PASUNDAN - CIREMAI  (COLOUR SERIES)"},
    {"id": 197, "name": "PASUNDAN - CIREMAI (BLACK SERIES)", "code": "PS_CIRE_BS", "description": "PASUNDAN - CIREMAI (BLACK SERIES)"},
    {"id": 198, "name": "PASUNDAN - CIWIDEY - BLACK SERIES", "code": "PS_CIWI_BS", "description": "PASUNDAN - CIWIDEY - BLACK SERIES"},
    {"id": 199, "name": "PASUNDAN - CIWIDEY", "code": "PS_CIWI_CS", "description": "PASUNDAN - CIWIDEY"},
    {"id": 200, "name": "PASUNDAN - KAMOJANG (BLACK SERIES)", "code": "PS_KAMO_BS", "description": "PASUNDAN - KAMOJANG (BLACK SERIES)"},
    {"id": 201, "name": "PASUNDAN - KAMOJANG (COLOUR SERIES)", "code": "PS_KAMO_CS", "description": "PASUNDAN - KAMOJANG (COLOUR SERIES)"},
    {"id": 202, "name": "PASUNDAN - KRAKATAU - BLACK SERIES", "code": "PS_KRAK_BS", "description": "PASUNDAN - KRAKATAU - BLACK SERIES"},
    {"id": 203, "name": "PASUNDAN - KRAKATAU", "code": "PS_KRAK_CS", "description": "PASUNDAN - KRAKATAU"},
    {"id": 204, "name": "PASUNDAN - LEMBANG (BLACK SERIES)", "code": "PS_LEM_BS", "description": "PASUNDAN - LEMBANG (BLACK SERIES)"},
    {"id": 205, "name": "PASUNDAN - LEMBANG (COLOUR SERIES)", "code": "PS_LEM_CS", "description": "PASUNDAN - LEMBANG (COLOUR SERIES)"},
    {"id": 206, "name": "PASUNDAN - LUHUR - BLACK SERIES", "code": "PS_LUH_BS", "description": "PASUNDAN - LUHUR - BLACK SERIES"},
    {"id": 207, "name": "PASUNDAN - LUHUR", "code": "PS_LUH_CS", "description": "PASUNDAN - LUHUR"},
    {"id": 208, "name": "PASUNDAN - MALABAR (BLACK SERIES)", "code": "PS_MAL_BS", "description": "PASUNDAN - MALABAR (BLACK SERIES)"},
    {"id": 209, "name": "PASUNDAN - MALABAR (COLOUR SERIES)", "code": "PS_MAL_CS", "description": "PASUNDAN - MALABAR (COLOUR SERIES)"},
    {"id": 210, "name": "PASUNDAN - MARIBAYA (BLACK SERIES)", "code": "PS_MAR_BS", "description": "PASUNDAN - MARIBAYA (BLACK SERIES)"},
    {"id": 211, "name": "PASUNDAN - MARIBAYA (COLOUR SERIES)", "code": "PS_MAR_CS", "description": "PASUNDAN - MARIBAYA (COLOUR SERIES)"},
    {"id": 212, "name": "PASUNDAN - PATUHA", "code": "PS_PATUHA", "description": "PASUNDAN - PATUHA"},
    {"id": 213, "name": "PASUNDAN - QRIS", "code": "PS_QRIS", "description": "PASUNDAN - QRIS"},
    {"id": 214, "name": "PASUNDAN - RENGGANIS", "code": "PS_RENG", "description": "PASUNDAN - RENGGANIS"},
    {"id": 215, "name": "BALI JUNIOR - TUMPAL KEMBANG", "code": "BJ_TK", "description": "Bali Junior Tumpal Kembang"},
    {"id": 216, "name": "BALI JUNIOR", "code": "BJ", "description": "Bali Junior"},
    {"id": 217, "name": "BATIK JUNIOR", "code": "BT_JR", "description": "Batik Junior"},
    {"id": 218, "name": "JUNIOR BALIMOON", "code": "JR_BM", "description": "Junior Balimoon"},
    {"id": 219, "name": "JUNIOR BATIK", "code": "JR_BT", "description": "Junior Batik"},
    {"id": 220, "name": "JUNIOR JACQUARD", "code": "JR_JC", "description": "Junior Jacquard"},
    {"id": 221, "name": "JUNIOR PRIMER 210", "code": "JR_PR210", "description": "Junior Primer 210"},
    {"id": 222, "name": "JUNIOR PRIMER DOMPET", "code": "JR_PRDM", "description": "Junior Primer Dompet"},
    {"id": 223, "name": "JUNIOR PRIMER EXCELLENT", "code": "JR_PREX", "description": "Junior Primer Excellent"},
    {"id": 224, "name": "JUNIOR PRIMER GRANDMASTER", "code": "JR_PRGM", "description": "Junior Primer Grandmaster"},
    {"id": 225, "name": "JUNIOR PRIMER NATURAL", "code": "JR_PRNT", "description": "Junior Primer Natural"},
    {"id": 226, "name": "JUNIOR TUMPAL KEMBANG", "code": "JR_TK", "description": "Junior Tumpal Kembang"},
    {"id": 227, "name": "JUNIOR VISCOSE LILIN PUTIH", "code": "JR_VLP", "description": "Junior Viscose Lilin Putih"},
    {"id": 228, "name": "JUNIOR VISCOSE", "code": "JR_VSC", "description": "Junior Viscose"},
    {"id": 229, "name": "KIDS CARNAVAL BALI PRINT", "code": "KC_BP", "description": "Kids Carnaval Bali Print"},
    {"id": 230, "name": "KIDS CARNAVAL GERIMIS 777", "code": "KC_G777", "description": "Kids Carnaval Gerimis 777"},
    {"id": 231, "name": "KIDS CARNAVAL JENTIK MANIS", "code": "KC_JM", "description": "Kids Carnaval Jentik Manis"},
    {"id": 232, "name": "KIDS CARNAVAL LUXURY", "code": "KC_LX", "description": "Kids Carnaval Luxury"},
    {"id": 233, "name": "KIDS CARNAVAL RELIEF DOBBY", "code": "KC_RDB", "description": "Kids Carnaval Relief Dobby"},
    {"id": 234, "name": "KIDS CARNAVAL SONGKET", "code": "KC_SG", "description": "Kids Carnaval Songket"},
    {"id": 235, "name": "SUBAIYAH - POLOS", "code": "SB_PL", "description": "Subaiyah Polos"},
    {"id": 236, "name": "SUBAIYAH - YAMANI", "code": "SB_YM", "description": "Subaiyah Yamani"},
    {"id": 237, "name": "SUBAIYAH 2 SISI", "code": "SB_2S", "description": "Subaiyah 2 Sisi"},
    {"id": 238, "name": "SUBAIYAH BURMA", "code": "SB_BR", "description": "Subaiyah Burma"},
    {"id": 239, "name": "SUBAIYAH DOBBY ZEBRA", "code": "SB_DZ", "description": "Subaiyah Dobby Zebra"},
    {"id": 240, "name": "SUBAIYAH JACQUARD", "code": "SB_JC", "description": "Subaiyah Jacquard"},
    {"id": 241, "name": "TIKAR CAPPUCCINO", "code": "TC", "description": "Tikar Cappuccino"},
    {"id": 242, "name": "TIKAR CAPPUCCINO - TIGADARA", "code": "TC_TD", "description": "Tikar Cappuccino Tiga Dara"},
    {"id": 243, "name": "TIKAR CAPPUCCINO - SERI PUTIH", "code": "TC_SP", "description": "Tikar Cappuccino Seri Putih"},
    {"id": 244, "name": "TIKAR CAPPUCCINO - SERI HITAM", "code": "TC_SH", "description": "Tikar Cappuccino Seri Hitam"},
    {"id": 245, "name": "TIKAR CAPPUCCINO - SERI HITAM PUTIH", "code": "TC_SHP", "description": "Tikar Cappuccino Seri Hitam Putih"},
    {"id": 246, "name": "TIKAR CAPPUCCINO - BOMBAY", "code": "TC_BM", "description": "Tikar Cappuccino Bombay"},
    {"id": 247, "name": "TIGA DARA 2025", "code": "TD25", "description": "Tiga Dara 2025"},
    {"id": 248, "name": "TEMANTEN", "code": "TMT", "description": "Temanten"},
    {"id": 249, "name": "TABUR", "code": "TBR", "description": "Tabur"},
    {"id": 250, "name": "SMALL HAWAI", "code": "SHW", "description": "Small Hawai"},
    {"id": 251, "name": "SMALL CHECK", "code": "SCK", "description": "Small Check"},
    {"id": 252, "name": "SAMARINDA", "code": "SMR", "description": "Samarinda"},
    {"id": 253, "name": "RAJA", "code": "RJA", "description": "Raja"},
    {"id": 254, "name": "PT3D (POLOS TUMPAL TIGA DARA)", "code": "PT3D", "description": "Polos Tumpal Tiga Dara"},
    {"id": 255, "name": "POLOS KHUSUS", "code": "PL_KH", "description": "Polos Khusus"},
    {"id": 256, "name": "POLOS HITAM TUMPAL LURIK", "code": "PL_HTL", "description": "Polos Hitam Tumpal Lurik"},
    {"id": 257, "name": "POLOS HITAM & PUTIH", "code": "PL_HP", "description": "Polos Hitam Putih"},
    {"id": 258, "name": "POLOS FC-SC", "code": "PL_FCSC", "description": "Polos FC SC"},
    {"id": 259, "name": "POLOS DENIM", "code": "PL_DNM", "description": "Polos Denim"},
    {"id": 260, "name": "PKB", "code": "PKB", "description": "PKB"},
    {"id": 261, "name": "PIUR", "code": "PIR", "description": "Piur"},
    {"id": 262, "name": "PADANG MINANG", "code": "PMN", "description": "Padang Minang"},
    {"id": 263, "name": "PADANG 2025", "code": "PD25", "description": "Padang 2025"},
    {"id": 264, "name": "P.K.M", "code": "PKM", "description": "PKM"},
    {"id": 265, "name": "P.K.K", "code": "PKK", "description": "PKK"},
    {"id": 266, "name": "MILLENIUM", "code": "MLN", "description": "Millenium"},
    {"id": 267, "name": "MANISE", "code": "MNS", "description": "Manise"},
    {"id": 268, "name": "MANISE KOTAK", "code": "MN_KT", "description": "Manise Kotak"},
    {"id": 269, "name": "MANISE 2 TEROPONG", "code": "MN_2T", "description": "Manise 2 Teropong"},
    {"id": 270, "name": "MANIK-MANIK", "code": "MM", "description": "Manik-Manik"},
    {"id": 271, "name": "MANDAR", "code": "MDR", "description": "Mandar"},
    {"id": 272, "name": "MANISE LILIN", "code": "MN_LL", "description": "Manise Lilin"},
    {"id": 273, "name": "MANISE HORIZON", "code": "MN_HR", "description": "Manise Horizon"},
    {"id": 274, "name": "LURIK", "code": "LRK", "description": "Lurik"},
    {"id": 275, "name": "LOBI", "code": "LBI", "description": "Lobi"},
    {"id": 276, "name": "LILIN FULL COLOUR", "code": "LL_FC", "description": "Lilin Full Colour"},
    {"id": 277, "name": "LILIN AAC", "code": "LL_AAC", "description": "Lilin AAC"},
    {"id": 278, "name": "KUPANG", "code": "KPG", "description": "Kupang"},
    {"id": 279, "name": "KOMBINASI 2025", "code": "KB25", "description": "Kombinasi 2025"},
    {"id": 280, "name": "KOMB JARI-JARI", "code": "KB_JJ", "description": "Kombinasi Jari-Jari"},
    {"id": 281, "name": "KEREN", "code": "KRN", "description": "Keren"},
    {"id": 282, "name": "KABAYAN", "code": "KBY", "description": "Kabayan"},
    {"id": 283, "name": "JARING EMAS (SC)", "code": "JE_SC", "description": "Jaring Emas SC"},
    {"id": 284, "name": "JARING EMAS - POLOS (SC)", "code": "JE_PL_SC", "description": "Jaring Emas Polos SC"},
    {"id": 285, "name": "JARING EMAS - PUTIH (SC)", "code": "JE_PT_SC", "description": "Jaring Emas Putih SC"},
    {"id": 286, "name": "JARING EMAS - HITAM (SC)", "code": "JE_HT_SC", "description": "Jaring Emas Hitam SC"},
    {"id": 287, "name": "JARING EMAS - MANISE (SC)", "code": "JE_MN_SC", "description": "Jaring Emas Manise SC"},
    {"id": 288, "name": "JARING EMAS - LILIN SC", "code": "JE_LL_SC", "description": "Jaring Emas Lilin SC"},
    {"id": 289, "name": "JARING EMAS - KOTAK", "code": "JE_KT", "description": "Jaring Emas Kotak"},
    {"id": 290, "name": "JARING EMAS - DONGGALA SC", "code": "JE_DG_SC", "description": "Jaring Emas Donggala SC"},
    {"id": 291, "name": "JARING EMAS (FC)", "code": "JE_FC", "description": "Jaring Emas FC"},
    {"id": 292, "name": "HORIZON ZEBRA", "code": "HZ_ZB", "description": "Horizon Zebra"},
    {"id": 293, "name": "HORIZON SC", "code": "HZ_SC", "description": "Horizon SC"},
    {"id": 294, "name": "HORIZON FC", "code": "HZ_FC", "description": "Horizon FC"},
    {"id": 295, "name": "HORIZON EMAS", "code": "HZ_EM", "description": "Horizon Emas"},
    {"id": 296, "name": "HORIZON - GRADASI 2025", "code": "HZ_GR25", "description": "Horizon Gradasi 2025"},
    {"id": 297, "name": "HITAM PUTIH", "code": "HP", "description": "Hitam Putih"},
    {"id": 298, "name": "HITAM MERAH", "code": "HM", "description": "Hitam Merah"},
    {"id": 299, "name": "HITAM MANIS", "code": "HMN", "description": "Hitam Manis"},
    {"id": 300, "name": "HAWAI", "code": "HW", "description": "Hawai"},
    {"id": 301, "name": "HAWAI ZEBRA", "code": "HW_ZB", "description": "Hawai Zebra"},
    {"id": 302, "name": "HAWAI KOTAK KECIL 2025", "code": "HW_KK25", "description": "Hawai Kotak Kecil 2025"},
    {"id": 303, "name": "GEMOY", "code": "GMY", "description": "Gemoy"},
    {"id": 304, "name": "ES LILIN KOMBINASI AAC", "code": "ELK_AAC", "description": "ES Lilin Kombinasi AAC"},
    {"id": 305, "name": "ES LILIN 2025", "code": "EL25", "description": "ES Lilin 2025"},
    {"id": 306, "name": "DUA SISI 2025", "code": "DS25", "description": "Dua Sisi 2025"},
    {"id": 307, "name": "DONGGALA PUTIH", "code": "DG_PT", "description": "Donggala Putih"},
    {"id": 308, "name": "DONGGALA HITAM & PUTIH", "code": "DG_HP", "description": "Donggala Hitam Putih"},
    {"id": 309, "name": "DONGGALA FC", "code": "DG_FC", "description": "Donggala FC"},
    {"id": 310, "name": "DONGGALA 2025", "code": "DG25", "description": "Donggala 2025"},
    {"id": 311, "name": "DONGGALA (EMAS)", "code": "DG_EM", "description": "Donggala Emas"},
    {"id": 312, "name": "DOLPHIN", "code": "DLP", "description": "Dolphin"},
    {"id": 313, "name": "CAPPUCCINO - SERI HITAM", "code": "CP_SH", "description": "Cappuccino Seri Hitam"},
    {"id": 314, "name": "BUGIS 2025", "code": "BG25", "description": "Bugis 2025"},
    {"id": 315, "name": "BOMBAY", "code": "BMB", "description": "Bombay"},
    {"id": 316, "name": "BOMBAY 2025", "code": "BMB25", "description": "Bombay 2025"},
    {"id": 317, "name": "BLACK SWEET", "code": "BSW", "description": "Black Sweet"},
    {"id": 318, "name": "BITINGAN 2025", "code": "BT25", "description": "Bitingan 2025"},
    {"id": 319, "name": "BARCELONA - LIRIS", "code": "BCL_LR", "description": "Barcelona Liris"},
    {"id": 320, "name": "BARCELONA - HITAM", "code": "BCL_HT", "description": "Barcelona Hitam"},
    {"id": 321, "name": "ALOHA", "code": "ALH", "description": "Aloha"},
    {"id": 322, "name": "ALAMANDA 2025", "code": "AL25", "description": "Alamanda 2025"},
    {"id": 323, "name": "AAC 2025", "code": "AAC25", "description": "AAC 2025"},
    {"id": 324, "name": "2 TEROPONG 2025", "code": "2TP25", "description": "2 Teropong 2025"},
    {"id": 325, "name": "POLOS HITAM TUMPAL WARNA", "code": "PL_HTW", "description": "Polos Hitam Tumpal Warna"},
    {"id": 326, "name": "DATU' - (SERI HITAM)", "code": "DT_SH", "description": "Datu Seri Hitam"},
    {"id": 327, "name": "DATU'", "code": "DT", "description": "Datu"},
    {"id": 328, "name": "MADRAS (SERI PUTIH)", "code": "MADRAS (SERI PUTIH)", "description": "MADRAS (SERI PUTIH)"},
    {"id": 329, "name": "MADRAS 555 - FULL COLOUR", "code": "MADRAS 555 - FULL COLOUR", "description": "MADRAS 555 - FULL COLOUR"},
    {"id": 330, "name": "MADRAS 555 - SERI HITAM", "code": "MADRAS 555 - SERI HITAM", "description": "MADRAS 555 - SERI HITAM"},
    {"id": 331, "name": "MADRAS 555 - SERI PUTIH", "code": "MADRAS 555 - SERI PUTIH", "description": "MADRAS 555 - SERI PUTIH"},
    {"id": 332, "name": "MADRAS", "code": "MADRAS", "description": "MADRAS"},
    {"id": 333, "name": "TIGA DARA - MADRAS - SERI PUTIH", "code": "TIGA DARA - MADRAS - SERI PUTIH", "description": "TIGA DARA - MADRAS - SERI PUTIH"},
    {"id": 334, "name": "TIGA DARA - MADRAS", "code": "TIGA DARA - MADRAS", "description": "TIGA DARA - MADRAS"},
    {"id": 335, "name": "MADRID - LUXURY", "code": "MADRID - LUXURY", "description": "MADRID - LUXURY"},
    {"id": 336, "name": "MADRID - MANIK MANIK", "code": "MADRID - MANIK MANIK", "description": "MADRID - MANIK MANIK"},
    {"id": 337, "name": "MADRID - TIGA DARA", "code": "MADRID - TIGA DARA", "description": "MADRID - TIGA DARA"},
    {"id": 338, "name": "MADRID - KOTAK", "code": "MADRID - KOTAK", "description": "MADRID - KOTAK"},
]

def seed_product_motifs():
    db = SessionLocal()

    try:
        for motif in MOTIFS:
            exists = db.query(ProductMotif).filter(
                (ProductMotif.code == motif["code"]) | (ProductMotif.name == motif["name"])
            ).first()

            if exists:
                if not exists.description and motif.get("description"):
                    exists.description = motif["description"]
                    print(f"  Updated description for {motif['code']}")
                else:
                    print(f"ProductMotif {motif['code']} already exists.")
                db.flush()
                continue

            motif_data = {k: v for k, v in motif.items() if k != "id"}
            db.add(ProductMotif(**motif_data))
            db.flush()

        db.commit()
        print("Product motifs seeded successfully.")

    except Exception as e:
        db.rollback()
        print(e)

    finally:
        db.close()


if __name__ == "__main__":
    seed_product_motifs()
