WORK_CATEGORIES = [
    "Video Editing",
    "Graphic Design",
    "Photography",
    "Videography",
    "Briefing & Coordination",
    "Project Management",
    "Campaign & Branding",
    "Content Planning",
    "Copywriting",
    "Translation",
    "Photo Editing",
    "Motion Graphic",
    "Content Review",
    "SEO",
    "Digital Marketing",
    "Social Media Content",
    "Marketplace Management",
    "Asset Management",
    "Data Backup",
    "Inventory Management",
    "Equipment Management",
    "Property Management",
    "Studio Management",
    "Showroom Management",
    "Display & Visual Merchandising",
    "Styling",
    "Talent Management",
    "Production Support",
    "Logistics",
    "Media Relations",
    "External Communication",
    "Quality Control",
    "Documentation",
    "Reporting",
    "KPI & Performance Review",
    "Budget Management",
    "Research & Development",
    "SOP & Workflow",
    "Brand Guidline",
    "Customer Experience",
]