export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    PROFILE: '/auth/me',
    REFRESH: '/auth/refresh',
  },
  DASHBOARD: {
    METRICS: '/dashboard',
  },
  WORK: '/work',
  INVENTORY: {
    ITEMS: '/inventory/items',
    TRANSACTIONS: '/inventory/transactions',
  },
  SCANNER: {
    LOCATION: '/inventory/scanner/location',
    IN: '/inventory/scanner/in',
    OUT: '/inventory/scanner/out',
  },
  CATEGORIES: '/categories',
  LOCATIONS: '/locations',
  PRODUCT_MASTER: '/product-master',
  PRODUCTS: '/products',
  PRODUCT_MOVEMENTS: '/product-movements',
  PRODUCT_STOCKS: '/product-stocks',
  REPORTS: '/reports',
  USERS: {
    LIST: '/users',
    PROFILE: '/users/profile'
  },
  EXPORT: '/export',
  SHOWROOM: {
    BASE: '/showroom',
    DASHBOARD: '/showroom/dashboard',
    STOCK: '/showroom/stock',
    TRANSFERS: '/showroom/transfers',
    STOCK_IN: '/showroom/stock-in',
    STOCK_OUT: '/showroom/stock-out',
    MOVEMENTS: '/showroom/movements',
    LOCATIONS: '/showroom/locations',
  },
  SHOWROOM_V2: {
    BASE: '/showroom-v2',
    DASHBOARD: '/showroom-v2/dashboard',
    SAMPLES: {
      STOCK: '/showroom-v2/samples/stock',
      HANDOVER: '/showroom-v2/samples/handover',
      TRANSFER: '/showroom-v2/samples/transfer',
      BORROW: '/showroom-v2/samples/borrow',
      RETURN: '/showroom-v2/samples/return',
      ADJUST: '/showroom-v2/samples/adjust',
      LOCATIONS: '/showroom-v2/samples/locations',
    },
    BORROWINGS: '/showroom-v2/borrowings',
    GUESTS: '/showroom-v2/guests',
    STOCK_CONTROL: {
      OPNAME: '/showroom-v2/stock-control/opname',
      RESTOCK: '/showroom-v2/stock-control/restock',
      MAINTENANCE: '/showroom-v2/stock-control/maintenance',
      RESERVATIONS: '/showroom-v2/stock-control/reservations',
    },
    REPORTS: {
      KPI: '/showroom-v2/reports/kpi',
      MOVEMENT_SUMMARY: '/showroom-v2/reports/movement-summary',
      STOCK_BY_LOCATION: '/showroom-v2/reports/stock-by-location',
      PRODUCT_HISTORY: '/showroom-v2/reports/product-history',
      BORROWING_SUMMARY: '/showroom-v2/reports/borrowing-summary',
      GUEST_SUMMARY: '/showroom-v2/reports/guest-summary',
    },
    MASTER_DATA: '/showroom-v2/master-data',
    SAMPLES_MOVEMENTS: '/showroom-v2/samples/movements',
    LOCATIONS_ALL: '/showroom-v2/samples/locations-all',
    PUBLIC: {
      SCAN: '/showroom-v2/public/scan',
    },
    STORAGE: {
      BASE: '/showroom-v2/storage',
      TREE: '/showroom-v2/storage/tree',
      QR: '/showroom-v2/storage/qr',
    },
    QR_SCAN: {
      RESOLVE: '/showroom-v2/qr/resolve',
      STORAGE: '/showroom-v2/qr/storage-scan',
      PRODUCT: '/showroom-v2/qr/product-scan',
    },
    DASHBOARD_V2: {
      SUMMARY: '/showroom-v2/dashboard',
      MOVEMENTS: '/showroom-v2/dashboard/movements',
      HEATMAP: '/showroom-v2/dashboard/heatmap',
      TRENDS: '/showroom-v2/dashboard/analytics/trends',
      TOP_PRODUCTS: '/showroom-v2/dashboard/analytics/top-products',
      BORROWING_ANALYTICS: '/showroom-v2/dashboard/analytics/borrowing',
      SNAPSHOT: '/showroom-v2/dashboard/snapshot',
      REBUILD_SUMMARY: '/showroom-v2/dashboard/rebuild-summary',
      SUMMARY_HISTORY: '/showroom-v2/dashboard/summary-history',
    },
    MANAGE: {
      BASE: '/showroom-v2/manage',
      REPORT: '/showroom-v2/manage/report',
      MOVEMENT_TYPES: '/showroom-v2/movement-types',
    },
    MOVEMENT_TYPES: {
      BASE: '/showroom-v2/movement-types',
    },
  },
  CLINIC: {
    BASE: '/clinic',
    MASTER_DATA: {
      PATIENT_PROFILES: '/clinic/master-data/patients',
      PATIENT_PROFILE: (id) => `/clinic/master-data/patients/${id}`,
      PATIENT_PROFILE_BY_EMPLOYEE: (eid) => `/clinic/master-data/patients/by-employee/${eid}`,
      PATIENT_PROFILE_BY_MR: (mr) => `/clinic/master-data/patients/by-mr/${mr}`,
      HEALTHCARE_PROFESSIONALS: '/clinic/master-data/healthcare-professionals',
      HEALTHCARE_PROFESSIONAL: (id) => `/clinic/master-data/healthcare-professionals/${id}`,
      ICD10_CODES: '/clinic/master-data/icd10-codes',
      ICD10_CODE: (id) => `/clinic/master-data/icd10-codes/${id}`,
      MEDICAL_PROCEDURES: '/clinic/master-data/medical-procedures',
      MEDICAL_PROCEDURE: (id) => `/clinic/master-data/medical-procedures/${id}`,
    },
    REGISTRATION: {
      QUEUES: '/clinic/registration/queues',
      QUEUE_CURRENT: '/clinic/registration/queues/current',
      QUEUE_WAITING_COUNT: '/clinic/registration/queues/waiting-count',
      QUEUE: (id) => `/clinic/registration/queues/${id}`,
      QUEUE_STATUS: (id) => `/clinic/registration/queues/${id}/status`,
      VISITS: '/clinic/registration/visits',
      VISIT: (id) => `/clinic/registration/visits/${id}`,
      VISIT_DETAIL: (id) => `/clinic/registration/visits/${id}/detail`,
      VISIT_CHECKIN: (id) => `/clinic/registration/visits/${id}/checkin`,
      VISIT_START_SERVING: (id) => `/clinic/registration/visits/${id}/start-serving`,
      VISIT_FINISH: (id) => `/clinic/registration/visits/${id}/finish`,
      VISIT_CANCEL: (id) => `/clinic/registration/visits/${id}/cancel`,
    },
    MEDICAL: {
      MEDICAL_RECORDS: '/clinic/medical/medical-records',
      MEDICAL_RECORD: (id) => `/clinic/medical/medical-records/${id}`,
      MEDICAL_RECORD_BY_VISIT: (vid) => `/clinic/medical/medical-records/by-visit/${vid}`,
      MEDICAL_RECORD_FINALIZE: (id) => `/clinic/medical/medical-records/${id}/finalize`,
      SOAP_NOTES: '/clinic/medical/soap-notes',
      SOAP_NOTE: (id) => `/clinic/medical/soap-notes/${id}`,
      SOAP_NOTE_BY_VISIT: (vid) => `/clinic/medical/soap-notes/by-visit/${vid}`,
      VITAL_SIGNS: '/clinic/medical/vital-signs',
      VITAL_SIGN: (id) => `/clinic/medical/vital-signs/${id}`,
      VITAL_SIGN_BY_VISIT: (vid) => `/clinic/medical/vital-signs/by-visit/${vid}`,
      DIAGNOSES_BY_VISIT: (vid) => `/clinic/medical/diagnoses/by-visit/${vid}`,
      DIAGNOSES: '/clinic/medical/diagnoses',
      DIAGNOSIS: (id) => `/clinic/medical/diagnoses/${id}`,
      VISIT_PROCEDURES_BY_VISIT: (vid) => `/clinic/medical/visit-procedures/by-visit/${vid}`,
      VISIT_PROCEDURES: '/clinic/medical/visit-procedures',
      VISIT_PROCEDURE: (id) => `/clinic/medical/visit-procedures/${id}`,
      ATTACHMENTS_BY_VISIT: (vid) => `/clinic/medical/medical-attachments/by-visit/${vid}`,
      ATTACHMENTS: '/clinic/medical/medical-attachments',
      ATTACHMENT: (id) => `/clinic/medical/medical-attachments/${id}`,
    },
    PHARMACY: {
      PRESCRIPTIONS: '/clinic/pharmacy/prescriptions',
      PRESCRIPTION: (id) => `/clinic/pharmacy/prescriptions/${id}`,
      PRESCRIPTION_BY_VISIT: (vid) => `/clinic/pharmacy/prescriptions/by-visit/${vid}`,
      PRESCRIPTION_DISPENSE: (id) => `/clinic/pharmacy/prescriptions/${id}/dispense`,
      PRESCRIPTION_CANCEL: (id) => `/clinic/pharmacy/prescriptions/${id}/cancel`,
      PRESCRIPTION_ITEMS_BY_RX: (rid) => `/clinic/pharmacy/prescription-items/by-prescription/${rid}`,
      PRESCRIPTION_ITEMS: '/clinic/pharmacy/prescription-items',
      PRESCRIPTION_ITEM: (id) => `/clinic/pharmacy/prescription-items/${id}`,
      MEDICINE_DISPENSES: '/clinic/pharmacy/medicine-dispenses',
      MEDICINE_DISPENSE: (id) => `/clinic/pharmacy/medicine-dispenses/${id}`,
    },
    CERTIFICATES: {
      MEDICAL_CERTIFICATES: '/clinic/certificates/medical-certificates',
      MEDICAL_CERTIFICATE: (id) => `/clinic/certificates/medical-certificates/${id}`,
      MEDICAL_CERTIFICATE_BY_VISIT: (vid) => `/clinic/certificates/medical-certificates/by-visit/${vid}`,
    },
    AUDIT: {
      ACTIVITY_LOGS: '/clinic/audit/activity-logs',
    },
  },
};

export default ENDPOINTS;
