"""employee_architecture_v2

Revision ID: 04e43f294820
Revises: ab970bd26d43
Create Date: 2026-07-21 21:51:11.210179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '04e43f294820'
down_revision: Union[str, Sequence[str], None] = 'ab970bd26d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('target_branch_id', sa.Integer(), nullable=True),
    sa.Column('target_department_id', sa.Integer(), nullable=True),
    sa.Column('target_position_id', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['target_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['target_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['target_position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_assignments_employee_id'), 'employee_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_assignments_id'), 'employee_assignments', ['id'], unique=False)
    op.create_table('employee_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_audits_employee_id'), 'employee_audits', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_audits_id'), 'employee_audits', ['id'], unique=False)
    op.create_table('employee_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('account_holder', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_banks_employee_id'), 'employee_banks', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_banks_id'), 'employee_banks', ['id'], unique=False)
    op.create_table('employee_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_contacts_employee_id'), 'employee_contacts', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_contacts_id'), 'employee_contacts', ['id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_documents_employee_id'), 'employee_documents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    op.create_table('employee_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('graduation_year', sa.String(length=4), nullable=True),
    sa.Column('gpa', sa.String(length=10), nullable=True),
    sa.Column('is_highest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_educations_employee_id'), 'employee_educations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_educations_id'), 'employee_educations', ['id'], unique=False)
    op.create_table('employee_emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_emergency_contacts_employee_id'), 'employee_emergency_contacts', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_emergency_contacts_id'), 'employee_emergency_contacts', ['id'], unique=False)
    op.create_table('employee_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_histories_employee_id'), 'employee_histories', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_histories_id'), 'employee_histories', ['id'], unique=False)
    op.drop_constraint('employee_profiles_ibfk_1', 'employee_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_employee_profiles_employee_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_id'), table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('employment_type', sa.Enum('PERMANENT', 'CONTRACT', 'INTERN', 'OUTSOURCE', 'PROBATION', name='employmenttype'), nullable=False))
    op.add_column('employees', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.alter_column('employees', 'employment_status',
               existing_type=mysql.ENUM('ACTIVE', 'PROBATION', 'CONTRACT', 'RESIGNED', 'TERMINATED'),
               type_=sa.Enum('ACTIVE', 'PROBATION', 'CONTRACT', 'INTERN', 'LEAVE', 'RESIGNED', 'TERMINATED', 'RETIRED', 'SUSPENDED', name='employmentstatus'),
               existing_nullable=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_foreign_key('fk_employees_company_id', 'employees', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('fk_employees_deleted_by', 'employees', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop FK constraints on child tables first (auto-generated names)
    op.drop_constraint('employee_histories_ibfk_1', 'employee_histories', type_='foreignkey')
    op.drop_constraint('employee_histories_ibfk_2', 'employee_histories', type_='foreignkey')
    op.drop_constraint('employee_histories_ibfk_3', 'employee_histories', type_='foreignkey')
    op.drop_constraint('employee_histories_ibfk_4', 'employee_histories', type_='foreignkey')
    op.drop_constraint('employee_histories_ibfk_5', 'employee_histories', type_='foreignkey')
    op.drop_constraint('employee_histories_ibfk_6', 'employee_histories', type_='foreignkey')
    op.drop_constraint('employee_assignments_ibfk_1', 'employee_assignments', type_='foreignkey')
    op.drop_constraint('employee_assignments_ibfk_2', 'employee_assignments', type_='foreignkey')
    op.drop_constraint('employee_assignments_ibfk_3', 'employee_assignments', type_='foreignkey')
    op.drop_constraint('employee_assignments_ibfk_4', 'employee_assignments', type_='foreignkey')
    op.drop_constraint('employee_assignments_ibfk_5', 'employee_assignments', type_='foreignkey')
    op.drop_constraint('employee_audits_ibfk_1', 'employee_audits', type_='foreignkey')
    op.drop_constraint('employee_audits_ibfk_2', 'employee_audits', type_='foreignkey')
    op.drop_constraint('employee_banks_ibfk_1', 'employee_banks', type_='foreignkey')
    op.drop_constraint('employee_contacts_ibfk_1', 'employee_contacts', type_='foreignkey')
    op.drop_constraint('employee_documents_ibfk_1', 'employee_documents', type_='foreignkey')
    op.drop_constraint('employee_documents_ibfk_2', 'employee_documents', type_='foreignkey')
    op.drop_constraint('employee_educations_ibfk_1', 'employee_educations', type_='foreignkey')
    op.drop_constraint('employee_emergency_contacts_ibfk_1', 'employee_emergency_contacts', type_='foreignkey')

    op.drop_constraint('fk_employees_company_id', 'employees', type_='foreignkey')
    op.drop_constraint('fk_employees_deleted_by', 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.alter_column('employees', 'employment_status',
               existing_type=sa.Enum('ACTIVE', 'PROBATION', 'CONTRACT', 'INTERN', 'LEAVE', 'RESIGNED', 'TERMINATED', 'RETIRED', 'SUSPENDED', name='employmentstatus'),
               type_=mysql.ENUM('ACTIVE', 'PROBATION', 'CONTRACT', 'RESIGNED', 'TERMINATED'),
               existing_nullable=False)
    op.drop_column('employees', 'deleted_by')
    op.drop_column('employees', 'deleted_at')
    op.drop_column('employees', 'employment_type')
    op.drop_column('employees', 'company_id')
    op.create_table('employee_profiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('emergency_contact_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bank_account', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bank_account_holder', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('education', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('skills', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_profiles_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_profiles_id'), 'employee_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_employee_id'), 'employee_profiles', ['employee_id'], unique=True)
    op.drop_index(op.f('ix_employee_histories_id'), table_name='employee_histories')
    op.drop_index(op.f('ix_employee_histories_employee_id'), table_name='employee_histories')
    op.drop_table('employee_histories')
    op.drop_index(op.f('ix_employee_emergency_contacts_id'), table_name='employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_emergency_contacts_employee_id'), table_name='employee_emergency_contacts')
    op.drop_table('employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_educations_id'), table_name='employee_educations')
    op.drop_index(op.f('ix_employee_educations_employee_id'), table_name='employee_educations')
    op.drop_table('employee_educations')
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_employee_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_employee_contacts_id'), table_name='employee_contacts')
    op.drop_index(op.f('ix_employee_contacts_employee_id'), table_name='employee_contacts')
    op.drop_table('employee_contacts')
    op.drop_index(op.f('ix_employee_banks_id'), table_name='employee_banks')
    op.drop_index(op.f('ix_employee_banks_employee_id'), table_name='employee_banks')
    op.drop_table('employee_banks')
    op.drop_index(op.f('ix_employee_audits_id'), table_name='employee_audits')
    op.drop_index(op.f('ix_employee_audits_employee_id'), table_name='employee_audits')
    op.drop_table('employee_audits')
    op.drop_index(op.f('ix_employee_assignments_id'), table_name='employee_assignments')
    op.drop_index(op.f('ix_employee_assignments_employee_id'), table_name='employee_assignments')
    op.drop_table('employee_assignments')
    # ### end Alembic commands ###
