"""Add worked_seconds and current_session_started_at

Revision ID: 06628bb8c6b7
Revises: 76bc2d06b839
Create Date: 2026-07-11 20:30:42.693514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06628bb8c6b7'
down_revision: Union[str, Sequence[str], None] = '76bc2d06b839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_activities', sa.Column('worked_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('work_activities', sa.Column('current_session_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # Backfill logic for old completed activities
    op.execute(
        """
        UPDATE work_activities 
        SET worked_seconds = TIMESTAMPDIFF(SECOND, start_time, end_time) 
        WHERE status = 'COMPLETED' AND start_time IS NOT NULL AND end_time IS NOT NULL;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_activities', 'current_session_started_at')
    op.drop_column('work_activities', 'worked_seconds')
    # ### end Alembic commands ###
