"""Add WorkAsset Model

Revision ID: 1fe9cfa9e03f
Revises: b28a0dab36c5
Create Date: 2026-07-10 15:51:08.660567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe9cfa9e03f'
down_revision: Union[str, Sequence[str], None] = 'b28a0dab36c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
