"""Add placement level, stock reserved, movement references

Revision ID: 35f36eb4ce1a
Revises: 766d3ed75581
Create Date: 2026-07-15 18:41:00.107989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f36eb4ce1a'
down_revision: Union[str, Sequence[str], None] = '766d3ed75581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_movements', sa.Column('reference_type', sa.String(length=50), nullable=True))
    op.add_column('product_movements', sa.Column('reference_id', sa.Integer(), nullable=True))
    op.add_column('product_placement_stocks', sa.Column('reserved_quantity', sa.Integer(), nullable=False))
    op.add_column('product_placements', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_placements', 'level')
    op.drop_column('product_placement_stocks', 'reserved_quantity')
    op.drop_column('product_movements', 'reference_id')
    op.drop_column('product_movements', 'reference_type')
    # ### end Alembic commands ###
