"""add_notifications

Revision ID: 3d1014852fbe
Revises: 009f9a607186
Create Date: 2026-07-21 19:54:21.705226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d1014852fbe'
down_revision: Union[str, Sequence[str], None] = '009f9a607186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('roles', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('showroom_daily_storage_summary', 'summary_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_showroom_daily_storage_summary_summary_date'), table_name='showroom_daily_storage_summary')
    op.create_index(op.f('ix_showroom_daily_storage_summary_summary_date'), 'showroom_daily_storage_summary', ['summary_date'], unique=True)
    op.alter_column('showroom_storage_snapshots', 'snapshot_type',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'NIGHTLY'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('showroom_storage_snapshots', 'snapshot_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'NIGHTLY'"))
    op.drop_index(op.f('ix_showroom_daily_storage_summary_summary_date'), table_name='showroom_daily_storage_summary')
    op.create_index(op.f('ix_showroom_daily_storage_summary_summary_date'), 'showroom_daily_storage_summary', ['summary_date'], unique=False)
    op.alter_column('showroom_daily_storage_summary', 'summary_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('roles', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
