"""employee_architecture_v4_enterprise_refinements

Revision ID: 4f2500b21ba9
Revises: a9513dca779c
Create Date: 2026-07-21 22:39:33.558036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f2500b21ba9'
down_revision: Union[str, Sequence[str], None] = 'a9513dca779c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_banks_code'), 'banks', ['code'], unique=True)
    op.create_index(op.f('ix_banks_id'), 'banks', ['id'], unique=False)
    op.create_table('employee_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_assets_employee_id'), 'employee_assets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_assets_id'), 'employee_assets', ['id'], unique=False)
    op.create_table('employee_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expired_at', sa.Date(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_file', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_certifications_employee_id'), 'employee_certifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_certifications_id'), 'employee_certifications', ['id'], unique=False)
    op.create_table('employee_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('basic_salary', sa.Integer(), nullable=True),
    sa.Column('document_file', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signed_by_employee', sa.Boolean(), nullable=True),
    sa.Column('signed_by_company', sa.Boolean(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_contracts_contract_number'), 'employee_contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_employee_contracts_employee_id'), 'employee_contracts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_contracts_id'), 'employee_contracts', ['id'], unique=False)
    op.create_table('employee_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_dependent', sa.Boolean(), nullable=True),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_families_employee_id'), 'employee_families', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_families_id'), 'employee_families', ['id'], unique=False)
    op.create_table('employee_personal_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('kk', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('identity_number', sa.String(length=50), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('bpjs_kesehatan', sa.String(length=50), nullable=True),
    sa.Column('bpjs_ketenagakerjaan', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_personal_infos_employee_id'), 'employee_personal_infos', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_personal_infos_id'), 'employee_personal_infos', ['id'], unique=False)
    op.create_table('employee_salary_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('basic_salary', sa.Integer(), nullable=True),
    sa.Column('allowance_transport', sa.Integer(), nullable=True),
    sa.Column('allowance_meal', sa.Integer(), nullable=True),
    sa.Column('allowance_position', sa.Integer(), nullable=True),
    sa.Column('allowance_communication', sa.Integer(), nullable=True),
    sa.Column('overtime_rate', sa.Integer(), nullable=True),
    sa.Column('salary_grade', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_salary_histories_employee_id'), 'employee_salary_histories', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_salary_histories_id'), 'employee_salary_histories', ['id'], unique=False)
    op.create_table('employee_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_flexible', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_shifts_employee_id'), 'employee_shifts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_shifts_id'), 'employee_shifts', ['id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('skill_category', sa.String(length=50), nullable=True),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_id'), 'employee_skills', ['id'], unique=False)
    op.drop_constraint('employee_personals_ibfk_1', 'employee_personals', type_='foreignkey')
    op.drop_index(op.f('ix_employee_personals_employee_id'), table_name='employee_personals')
    op.drop_index(op.f('ix_employee_personals_id'), table_name='employee_personals')
    op.drop_table('employee_personals')
    op.add_column('employee_assignments', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employee_assignments_created_by', 'employee_assignments', 'users', ['created_by_user_id'], ['id'])
    op.drop_column('employee_assignments', 'created_by')
    op.add_column('employee_audits', sa.Column('changed_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employee_audits_changed_by_user_id', 'employee_audits', 'users', ['changed_by_user_id'], ['id'])
    op.drop_column('employee_audits', 'changed_by')
    op.add_column('employee_banks', sa.Column('bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employee_banks_bank_id', 'employee_banks', 'banks', ['bank_id'], ['id'])
    op.drop_column('employee_banks', 'bank_name')
    op.add_column('employee_contacts', sa.Column('contact_type', sa.String(length=20), nullable=False))
    op.add_column('employee_contacts', sa.Column('label', sa.String(length=50), nullable=True))
    op.add_column('employee_contacts', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('employee_contacts_ibfk_1'), 'employee_contacts', type_='foreignkey')
    op.drop_index(op.f('ix_employee_contacts_employee_id'), table_name='employee_contacts')
    op.create_index(op.f('ix_employee_contacts_employee_id'), 'employee_contacts', ['employee_id'], unique=False)
    op.create_foreign_key('employee_contacts_ibfk_1', 'employee_contacts', 'employees', ['employee_id'], ['id'])
    op.add_column('employee_documents', sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('employee_documents_ibfk_2'), 'employee_documents', type_='foreignkey')
    op.create_foreign_key('fk_employee_documents_uploaded_by_user_id', 'employee_documents', 'users', ['uploaded_by_user_id'], ['id'])
    op.drop_column('employee_documents', 'uploaded_by')
    op.add_column('employee_educations', sa.Column('start_year', sa.String(length=4), nullable=True))
    op.add_column('employee_educations', sa.Column('end_year', sa.String(length=4), nullable=True))
    op.add_column('employee_histories', sa.Column('changed_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('employee_histories_ibfk_2'), 'employee_histories', type_='foreignkey')
    op.create_foreign_key('fk_employee_histories_changed_by_user_id', 'employee_histories', 'users', ['changed_by_user_id'], ['id'])
    op.drop_column('employee_histories', 'changed_by')
    op.add_column('employees', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_employees_deleted_by'), 'employees', type_='foreignkey')
    op.create_foreign_key('fk_employees_deleted_by_user_id', 'employees', 'users', ['deleted_by_user_id'], ['id'])
    op.drop_column('employees', 'deleted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_employees_deleted_by_user_id', 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employees_deleted_by'), 'employees', 'users', ['deleted_by'], ['id'])
    op.drop_column('employees', 'deleted_by_user_id')
    op.add_column('employee_histories', sa.Column('changed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_employee_histories_changed_by_user_id', 'employee_histories', type_='foreignkey')
    op.create_foreign_key(op.f('employee_histories_ibfk_2'), 'employee_histories', 'users', ['changed_by'], ['id'])
    op.drop_column('employee_histories', 'changed_by_user_id')
    op.drop_column('employee_educations', 'end_year')
    op.drop_column('employee_educations', 'start_year')
    op.add_column('employee_documents', sa.Column('uploaded_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_employee_documents_uploaded_by_user_id', 'employee_documents', type_='foreignkey')
    op.create_foreign_key(op.f('employee_documents_ibfk_2'), 'employee_documents', 'users', ['uploaded_by'], ['id'])
    op.drop_column('employee_documents', 'uploaded_by_user_id')
    op.drop_constraint('employee_contacts_ibfk_1', 'employee_contacts', type_='foreignkey')
    op.drop_index(op.f('ix_employee_contacts_employee_id'), table_name='employee_contacts')
    op.create_index(op.f('ix_employee_contacts_employee_id'), 'employee_contacts', ['employee_id'], unique=True)
    op.create_foreign_key(op.f('employee_contacts_ibfk_1'), 'employee_contacts', 'employees', ['employee_id'], ['id'])
    op.drop_column('employee_contacts', 'is_primary')
    op.drop_column('employee_contacts', 'label')
    op.drop_column('employee_contacts', 'contact_type')
    op.add_column('employee_banks', sa.Column('bank_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint('fk_employee_banks_bank_id', 'employee_banks', type_='foreignkey')
    op.drop_column('employee_banks', 'bank_id')
    op.add_column('employee_audits', sa.Column('changed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_employee_audits_changed_by_user_id', 'employee_audits', type_='foreignkey')
    op.drop_column('employee_audits', 'changed_by_user_id')
    op.add_column('employee_assignments', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_employee_assignments_created_by', 'employee_assignments', type_='foreignkey')
    op.drop_column('employee_assignments', 'created_by_user_id')
    op.create_table('employee_personals',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nik', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('kk', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('birth_place', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('religion', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('marital_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('nationality', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('blood_type', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('photo', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('identity_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tax_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bpjs_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_personals_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_personals_id'), 'employee_personals', ['id'], unique=False)
    op.create_index(op.f('ix_employee_personals_employee_id'), 'employee_personals', ['employee_id'], unique=True)
    op.drop_table('employee_skills')
    op.drop_table('employee_shifts')
    op.drop_table('employee_salary_histories')
    op.drop_table('employee_personal_infos')
    op.drop_table('employee_families')
    op.drop_table('employee_contracts')
    op.drop_table('employee_certifications')
    op.drop_table('employee_assets')
    op.drop_table('banks')
    # ### end Alembic commands ###
