"""Add Work Activity Models WA-01

Revision ID: 553a116b2b8c
Revises: a56bcf61321f
Create Date: 2026-07-09 23:32:53.705200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553a116b2b8c'
down_revision: Union[str, Sequence[str], None] = 'a56bcf61321f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    op.create_index(op.f('ix_divisions_name'), 'divisions', ['name'], unique=True)
    op.create_table('work_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_categories_id'), 'work_categories', ['id'], unique=False)
    op.create_index(op.f('ix_work_categories_name'), 'work_categories', ['name'], unique=True)
    op.create_table('work_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('READY', 'WORKING', 'PAUSED', 'COMPLETED', 'CANCELLED', name='workactivitystatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('photo_before', sa.String(length=255), nullable=True),
    sa.Column('photo_after', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['work_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_activities_id'), 'work_activities', ['id'], unique=False)
    op.add_column('users', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'divisions', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'division_id')
    op.drop_index(op.f('ix_work_activities_id'), table_name='work_activities')
    op.drop_table('work_activities')
    op.drop_index(op.f('ix_work_categories_name'), table_name='work_categories')
    op.drop_index(op.f('ix_work_categories_id'), table_name='work_categories')
    op.drop_table('work_categories')
    op.drop_index(op.f('ix_divisions_name'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
