"""Add Work Evidence Models WA-02

Revision ID: 6e0f74bd23cb
Revises: 553a116b2b8c
Create Date: 2026-07-10 08:17:00.483770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e0f74bd23cb'
down_revision: Union[str, Sequence[str], None] = '553a116b2b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_activity_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BEFORE', 'PROGRESS', 'AFTER', name='workevidencetype'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('evidence_order', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_activity_id'], ['work_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_evidences_id'), 'work_evidences', ['id'], unique=False)
    op.drop_column('work_activities', 'photo_after')
    op.drop_column('work_activities', 'photo_before')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_activities', sa.Column('photo_before', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('work_activities', sa.Column('photo_after', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_work_evidences_id'), table_name='work_evidences')
    op.drop_table('work_evidences')
    # ### end Alembic commands ###
