"""Add product placements and movement engine

Revision ID: 766d3ed75581
Revises: 06628bb8c6b7
Create Date: 2026-07-15 18:27:38.284874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '766d3ed75581'
down_revision: Union[str, Sequence[str], None] = '06628bb8c6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_types_id'), 'placement_types', ['id'], unique=False)
    op.create_index(op.f('ix_placement_types_name'), 'placement_types', ['name'], unique=True)
    op.create_table('product_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_placements.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['placement_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_placements_code'), 'product_placements', ['code'], unique=True)
    op.create_index(op.f('ix_product_placements_id'), 'product_placements', ['id'], unique=False)
    op.create_index(op.f('ix_product_placements_name'), 'product_placements', ['name'], unique=False)
    op.create_table('product_placement_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['product_placements.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'placement_id', name='uix_product_placement_stock')
    )
    op.create_index(op.f('ix_product_placement_stocks_id'), 'product_placement_stocks', ['id'], unique=False)
    # op.drop_index(op.f('ix_product_stocks_id'), table_name='product_stocks')
    # op.drop_index('uix_product_location_stock', table_name='product_stocks')
    # op.drop_table('product_stocks')
    op.add_column('product_movements', sa.Column('reason', sa.Enum('RECEIVE_FROM_FACTORY', 'SHOWROOM_TRANSFER', 'GIFT', 'SALES_SAMPLE', 'PHOTO_SHOOT', 'TV_STUDIO', 'DAMAGED', 'MISSING', 'STOCK_OPNAME', 'OTHER', name='productmovementreason'), nullable=False))
    op.add_column('product_movements', sa.Column('source_placement_id', sa.Integer(), nullable=True))
    op.add_column('product_movements', sa.Column('destination_placement_id', sa.Integer(), nullable=True))
    op.alter_column('product_movements', 'type',
               existing_type=mysql.ENUM('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('IN', 'OUT', 'TRANSFER', name='productmovementtype'),
               existing_nullable=False)
    op.drop_constraint(op.f('product_movements_ibfk_3'), 'product_movements', type_='foreignkey')
    op.drop_constraint(op.f('product_movements_ibfk_1'), 'product_movements', type_='foreignkey')
    op.create_foreign_key(None, 'product_movements', 'product_placements', ['destination_placement_id'], ['id'])
    op.create_foreign_key(None, 'product_movements', 'product_placements', ['source_placement_id'], ['id'])
    op.drop_column('product_movements', 'source_location_id')
    op.drop_column('product_movements', 'destination_location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_movements', sa.Column('destination_location_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_movements', sa.Column('source_location_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_movements', type_='foreignkey')
    op.drop_constraint(None, 'product_movements', type_='foreignkey')
    op.create_foreign_key(op.f('product_movements_ibfk_1'), 'product_movements', 'locations', ['destination_location_id'], ['id'])
    op.create_foreign_key(op.f('product_movements_ibfk_3'), 'product_movements', 'locations', ['source_location_id'], ['id'])
    op.alter_column('product_movements', 'type',
               existing_type=sa.Enum('IN', 'OUT', 'TRANSFER', name='productmovementtype'),
               type_=mysql.ENUM('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('product_movements', 'destination_placement_id')
    op.drop_column('product_movements', 'source_placement_id')
    op.drop_column('product_movements', 'reason')
    op.create_table('product_stocks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('product_stocks_ibfk_1')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_stocks_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uix_product_location_stock'), 'product_stocks', ['product_id', 'location_id'], unique=True)
    op.create_index(op.f('ix_product_stocks_id'), 'product_stocks', ['id'], unique=False)
    op.drop_index(op.f('ix_product_placement_stocks_id'), table_name='product_placement_stocks')
    op.drop_table('product_placement_stocks')
    op.drop_index(op.f('ix_product_placements_name'), table_name='product_placements')
    op.drop_index(op.f('ix_product_placements_id'), table_name='product_placements')
    op.drop_index(op.f('ix_product_placements_code'), table_name='product_placements')
    op.drop_table('product_placements')
    op.drop_index(op.f('ix_placement_types_name'), table_name='placement_types')
    op.drop_index(op.f('ix_placement_types_id'), table_name='placement_types')
    op.drop_table('placement_types')
    # ### end Alembic commands ###
