"""Add ADJUSTMENT to ProductMovementType

Revision ID: 772cc5c144c7
Revises: a932daa8678f
Create Date: 2026-07-08 00:21:07.231513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '772cc5c144c7'
down_revision: Union[str, Sequence[str], None] = 'a932daa8678f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_movements', 'type',
               existing_type=mysql.ENUM('IN', 'OUT', 'TRANSFER'),
               type_=sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='productmovementtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_movements', 'type',
               existing_type=sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='productmovementtype'),
               type_=mysql.ENUM('IN', 'OUT', 'TRANSFER'),
               existing_nullable=False)
    # ### end Alembic commands ###
