"""Add product master models

Revision ID: 84b59e796d8a
Revises: 1f9de6368b81
Create Date: 2026-07-07 23:22:21.889282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b59e796d8a'
down_revision: Union[str, Sequence[str], None] = '1f9de6368b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_code'), 'product_categories', ['code'], unique=True)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_table('product_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_colors_code'), 'product_colors', ['code'], unique=True)
    op.create_index(op.f('ix_product_colors_id'), 'product_colors', ['id'], unique=False)
    op.create_index(op.f('ix_product_colors_name'), 'product_colors', ['name'], unique=True)
    op.create_table('product_motifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_motifs_code'), 'product_motifs', ['code'], unique=True)
    op.create_index(op.f('ix_product_motifs_id'), 'product_motifs', ['id'], unique=False)
    op.create_index(op.f('ix_product_motifs_name'), 'product_motifs', ['name'], unique=True)
    op.create_table('product_sub_motifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sub_motifs_code'), 'product_sub_motifs', ['code'], unique=True)
    op.create_index(op.f('ix_product_sub_motifs_id'), 'product_sub_motifs', ['id'], unique=False)
    op.create_index(op.f('ix_product_sub_motifs_name'), 'product_sub_motifs', ['name'], unique=True)
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_types_code'), 'product_types', ['code'], unique=True)
    op.create_index(op.f('ix_product_types_id'), 'product_types', ['id'], unique=False)
    op.create_index(op.f('ix_product_types_name'), 'product_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_types_name'), table_name='product_types')
    op.drop_index(op.f('ix_product_types_id'), table_name='product_types')
    op.drop_index(op.f('ix_product_types_code'), table_name='product_types')
    op.drop_table('product_types')
    op.drop_index(op.f('ix_product_sub_motifs_name'), table_name='product_sub_motifs')
    op.drop_index(op.f('ix_product_sub_motifs_id'), table_name='product_sub_motifs')
    op.drop_index(op.f('ix_product_sub_motifs_code'), table_name='product_sub_motifs')
    op.drop_table('product_sub_motifs')
    op.drop_index(op.f('ix_product_motifs_name'), table_name='product_motifs')
    op.drop_index(op.f('ix_product_motifs_id'), table_name='product_motifs')
    op.drop_index(op.f('ix_product_motifs_code'), table_name='product_motifs')
    op.drop_table('product_motifs')
    op.drop_index(op.f('ix_product_colors_name'), table_name='product_colors')
    op.drop_index(op.f('ix_product_colors_id'), table_name='product_colors')
    op.drop_index(op.f('ix_product_colors_code'), table_name='product_colors')
    op.drop_table('product_colors')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_code'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
