"""add_showroom_v2_tables

Revision ID: 8d25a464bff9
Revises: 78081b401cbd
Create Date: 2026-07-18 17:14:10.452291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d25a464bff9'
down_revision: Union[str, Sequence[str], None] = '78081b401cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showroom_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_locations_code'), 'showroom_locations', ['code'], unique=True)
    op.create_index(op.f('ix_showroom_locations_id'), 'showroom_locations', ['id'], unique=False)
    op.create_table('showroom_barcode_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_barcode_scans_id'), 'showroom_barcode_scans', ['id'], unique=False)
    op.create_table('showroom_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('HANDOVER', 'TRANSFER', 'BORROW', 'RETURN', 'RELEASE', 'ADJUSTMENT', name='showroommovementtype'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_movements_id'), 'showroom_movements', ['id'], unique=False)
    op.create_table('showroom_opname_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'APPROVED', name='showroomopnamestatus'), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['showroom_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_opname_sessions_id'), 'showroom_opname_sessions', ['id'], unique=False)
    op.create_table('showroom_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_by', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('reserved_from', sa.Date(), nullable=False),
    sa.Column('reserved_until', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='showroomreservationstatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reserved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_reservations_id'), 'showroom_reservations', ['id'], unique=False)
    op.create_table('showroom_restock_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('minimum_quantity', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'COMPLETED', 'CANCELLED', name='showroomrestockstatus'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_restock_requests_id'), 'showroom_restock_requests', ['id'], unique=False)
    op.create_table('showroom_sample_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uix_showroom_stock_product_location')
    )
    op.create_index(op.f('ix_showroom_sample_stocks_id'), 'showroom_sample_stocks', ['id'], unique=False)
    op.create_table('showroom_borrowings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('borrower_name', sa.String(length=100), nullable=True),
    sa.Column('borrower_location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('borrow_date', sa.Date(), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BORROWED', 'RETURNED', 'CANCELLED', name='showroomborrowingstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('return_movement_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['borrower_location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['showroom_movements.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_movement_id'], ['showroom_movements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_borrowings_id'), 'showroom_borrowings', ['id'], unique=False)
    op.create_table('showroom_guest_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_company', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['showroom_movements.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_guest_releases_id'), 'showroom_guest_releases', ['id'], unique=False)
    op.create_table('showroom_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.Enum('LAUNDRY', 'REPAIR', 'CLEANING', 'OTHER', name='showroommaintenancetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='showroommaintenancestatus'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('return_movement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['showroom_movements.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_movement_id'], ['showroom_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_maintenance_id'), 'showroom_maintenance', ['id'], unique=False)
    op.create_table('showroom_opname_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('variance', sa.Integer(), nullable=True),
    sa.Column('adjustment_movement_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjustment_movement_id'], ['showroom_movements.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['showroom_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['showroom_opname_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showroom_opname_items_id'), 'showroom_opname_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showroom_opname_items_id'), table_name='showroom_opname_items')
    op.drop_table('showroom_opname_items')
    op.drop_index(op.f('ix_showroom_maintenance_id'), table_name='showroom_maintenance')
    op.drop_table('showroom_maintenance')
    op.drop_index(op.f('ix_showroom_guest_releases_id'), table_name='showroom_guest_releases')
    op.drop_table('showroom_guest_releases')
    op.drop_index(op.f('ix_showroom_borrowings_id'), table_name='showroom_borrowings')
    op.drop_table('showroom_borrowings')
    op.drop_index(op.f('ix_showroom_sample_stocks_id'), table_name='showroom_sample_stocks')
    op.drop_table('showroom_sample_stocks')
    op.drop_index(op.f('ix_showroom_restock_requests_id'), table_name='showroom_restock_requests')
    op.drop_table('showroom_restock_requests')
    op.drop_index(op.f('ix_showroom_reservations_id'), table_name='showroom_reservations')
    op.drop_table('showroom_reservations')
    op.drop_index(op.f('ix_showroom_opname_sessions_id'), table_name='showroom_opname_sessions')
    op.drop_table('showroom_opname_sessions')
    op.drop_index(op.f('ix_showroom_movements_id'), table_name='showroom_movements')
    op.drop_table('showroom_movements')
    op.drop_index(op.f('ix_showroom_barcode_scans_id'), table_name='showroom_barcode_scans')
    op.drop_table('showroom_barcode_scans')
    op.drop_index(op.f('ix_showroom_locations_id'), table_name='showroom_locations')
    op.drop_index(op.f('ix_showroom_locations_code'), table_name='showroom_locations')
    op.drop_table('showroom_locations')
    # ### end Alembic commands ###
