"""Refactor Inventory Transactions

Revision ID: a56bcf61321f
Revises: 772cc5c144c7
Create Date: 2026-07-09 20:47:24.374981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a56bcf61321f'
down_revision: Union[str, Sequence[str], None] = '772cc5c144c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'location_id', name='uix_item_location_stock')
    )
    op.create_index(op.f('ix_item_stocks_id'), 'item_stocks', ['id'], unique=False)
    op.add_column('inventory_transactions', sa.Column('type', sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='inventorymovementtype'), nullable=False))
    op.add_column('inventory_transactions', sa.Column('source_location_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('destination_location_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('reference', sa.String(length=255), nullable=True))
    op.add_column('inventory_transactions', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('inventory_transactions', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.create_foreign_key(None, 'inventory_transactions', 'locations', ['destination_location_id'], ['id'])
    op.create_foreign_key(None, 'inventory_transactions', 'locations', ['source_location_id'], ['id'])
    # Data Migration: Move Item.stock_qty into item_stocks based on Item.location_id
    op.execute("""
        INSERT INTO item_stocks (item_id, location_id, quantity)
        SELECT id, COALESCE(location_id, 1), stock_qty FROM items WHERE stock_qty > 0
    """)
    
    op.drop_column('inventory_transactions', 'remarks')
    op.drop_column('inventory_transactions', 'transaction_type')
    op.drop_column('inventory_transactions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('transaction_type', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('inventory_transactions', sa.Column('remarks', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.drop_column('inventory_transactions', 'notes')
    op.drop_column('inventory_transactions', 'date')
    op.drop_column('inventory_transactions', 'reference')
    op.drop_column('inventory_transactions', 'destination_location_id')
    op.drop_column('inventory_transactions', 'source_location_id')
    op.drop_column('inventory_transactions', 'type')
    op.drop_index(op.f('ix_item_stocks_id'), table_name='item_stocks')
    op.drop_table('item_stocks')
    # ### end Alembic commands ###
