"""employee_architecture_v3_enterprise

Revision ID: a9513dca779c
Revises: 04e43f294820
Create Date: 2026-07-21 22:07:14.171574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9513dca779c'
down_revision: Union[str, Sequence[str], None] = '04e43f294820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_job_levels_code'), 'job_levels', ['code'], unique=True)
    op.create_index(op.f('ix_job_levels_id'), 'job_levels', ['id'], unique=False)
    op.create_table('employee_personals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('kk', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('identity_number', sa.String(length=50), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('bpjs_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_employee_personals_employee_id'), 'employee_personals', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_personals_id'), 'employee_personals', ['id'], unique=False)
    op.add_column('employee_assignments', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('employee_audits', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('employee_audits', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('employee_banks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('employee_banks', sa.Column('is_payroll', sa.Boolean(), nullable=True))
    op.drop_constraint('employee_banks_ibfk_1', 'employee_banks', type_='foreignkey')
    op.drop_index(op.f('ix_employee_banks_employee_id'), table_name='employee_banks')
    op.create_index(op.f('ix_employee_banks_employee_id'), 'employee_banks', ['employee_id'], unique=False)
    op.create_foreign_key('employee_banks_ibfk_1', 'employee_banks', 'employees', ['employee_id'], ['id'])
    op.add_column('employee_contacts', sa.Column('current_address', sa.Text(), nullable=True))
    op.add_column('employee_contacts', sa.Column('current_province', sa.String(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('current_city', sa.String(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('current_district', sa.String(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('current_postal_code', sa.String(length=20), nullable=True))
    op.add_column('employee_contacts', sa.Column('permanent_address', sa.Text(), nullable=True))
    op.add_column('employee_contacts', sa.Column('permanent_province', sa.String(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('permanent_city', sa.String(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('permanent_district', sa.String(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('permanent_postal_code', sa.String(length=20), nullable=True))
    op.drop_column('employee_contacts', 'city')
    op.drop_column('employee_contacts', 'district')
    op.drop_column('employee_contacts', 'address')
    op.drop_column('employee_contacts', 'postal_code')
    op.drop_column('employee_contacts', 'province')
    op.add_column('employee_documents', sa.Column('document_number', sa.String(length=100), nullable=True))
    op.add_column('employee_documents', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('employee_documents', sa.Column('expired_at', sa.Date(), nullable=True))
    op.add_column('employee_educations', sa.Column('certificate_number', sa.String(length=100), nullable=True))
    op.add_column('employee_educations', sa.Column('graduated', sa.Boolean(), nullable=True))
    op.add_column('employee_emergency_contacts', sa.Column('is_primary', sa.Boolean(), nullable=True))
    op.drop_constraint('employee_emergency_contacts_ibfk_1', 'employee_emergency_contacts', type_='foreignkey')
    op.drop_index(op.f('ix_employee_emergency_contacts_employee_id'), table_name='employee_emergency_contacts')
    op.create_index(op.f('ix_employee_emergency_contacts_employee_id'), 'employee_emergency_contacts', ['employee_id'], unique=False)
    op.create_foreign_key('employee_emergency_contacts_ibfk_1', 'employee_emergency_contacts', 'employees', ['employee_id'], ['id'])
    op.add_column('employee_histories', sa.Column('job_level_id', sa.Integer(), nullable=True))
    op.add_column('employee_histories', sa.Column('salary_grade', sa.String(length=50), nullable=True))
    op.create_foreign_key('fk_employee_histories_job_level_id', 'employee_histories', 'job_levels', ['job_level_id'], ['id'])
    op.add_column('employees', sa.Column('job_level_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('delete_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_employees_job_level_id'), 'employees', ['job_level_id'], unique=False)
    op.create_foreign_key('fk_employees_job_level_id', 'employees', 'job_levels', ['job_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_job_level_id', 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_job_level_id'), table_name='employees')
    op.drop_column('employees', 'delete_reason')
    op.drop_column('employees', 'job_level_id')
    op.drop_constraint('fk_employee_histories_job_level_id', 'employee_histories', type_='foreignkey')
    op.drop_column('employee_histories', 'salary_grade')
    op.drop_column('employee_histories', 'job_level_id')
    op.drop_constraint('employee_emergency_contacts_ibfk_1', 'employee_emergency_contacts', type_='foreignkey')
    op.drop_index(op.f('ix_employee_emergency_contacts_employee_id'), table_name='employee_emergency_contacts')
    op.create_index(op.f('ix_employee_emergency_contacts_employee_id'), 'employee_emergency_contacts', ['employee_id'], unique=True)
    op.create_foreign_key('employee_emergency_contacts_ibfk_1', 'employee_emergency_contacts', 'employees', ['employee_id'], ['id'])
    op.drop_column('employee_emergency_contacts', 'is_primary')
    op.drop_column('employee_educations', 'graduated')
    op.drop_column('employee_educations', 'certificate_number')
    op.drop_column('employee_documents', 'expired_at')
    op.drop_column('employee_documents', 'issue_date')
    op.drop_column('employee_documents', 'document_number')
    op.add_column('employee_contacts', sa.Column('province', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('postal_code', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('employee_contacts', sa.Column('address', mysql.TEXT(), nullable=True))
    op.add_column('employee_contacts', sa.Column('district', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('employee_contacts', sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('employee_contacts', 'permanent_postal_code')
    op.drop_column('employee_contacts', 'permanent_district')
    op.drop_column('employee_contacts', 'permanent_city')
    op.drop_column('employee_contacts', 'permanent_province')
    op.drop_column('employee_contacts', 'permanent_address')
    op.drop_column('employee_contacts', 'current_postal_code')
    op.drop_column('employee_contacts', 'current_district')
    op.drop_column('employee_contacts', 'current_city')
    op.drop_column('employee_contacts', 'current_province')
    op.drop_column('employee_contacts', 'current_address')
    op.drop_constraint('employee_banks_ibfk_1', 'employee_banks', type_='foreignkey')
    op.drop_index(op.f('ix_employee_banks_employee_id'), table_name='employee_banks')
    op.create_index(op.f('ix_employee_banks_employee_id'), 'employee_banks', ['employee_id'], unique=True)
    op.create_foreign_key('employee_banks_ibfk_1', 'employee_banks', 'employees', ['employee_id'], ['id'])
    op.drop_column('employee_banks', 'is_payroll')
    op.drop_column('employee_banks', 'priority')
    op.drop_column('employee_audits', 'user_agent')
    op.drop_column('employee_audits', 'ip_address')
    op.drop_column('employee_assignments', 'status')
    op.drop_constraint('employee_personals_ibfk_1', 'employee_personals', type_='foreignkey')
    op.drop_index(op.f('ix_employee_personals_id'), table_name='employee_personals')
    op.drop_index(op.f('ix_employee_personals_employee_id'), table_name='employee_personals')
    op.drop_table('employee_personals')
    op.drop_index(op.f('ix_job_levels_id'), table_name='job_levels')
    op.drop_index(op.f('ix_job_levels_code'), table_name='job_levels')
    op.drop_table('job_levels')
    # ### end Alembic commands ###
