"""Add Work Asset Model WA-04

Revision ID: b28a0dab36c5
Revises: 6e0f74bd23cb
Create Date: 2026-07-10 15:44:57.841721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28a0dab36c5'
down_revision: Union[str, Sequence[str], None] = '6e0f74bd23cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
